# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-09 15:49
from __future__ import unicode_literals

import allauth.socialaccount.fields
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20190325_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='extra_data_encrypted',
            field=django_cryptography.fields.encrypt(allauth.socialaccount.fields.JSONField(default=dict, verbose_name='extra data')),
        ),
        migrations.AddField(
            model_name='socialapp',
            name='client_id_encrypted',
            field=django_cryptography.fields.encrypt(models.CharField(default='', help_text='App ID, or consumer key', max_length=2000, verbose_name='client id')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialapp',
            name='key_encrypted',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Key', max_length=2000, verbose_name='key')),
        ),
        migrations.AddField(
            model_name='socialapp',
            name='secret_encrypted',
            field=django_cryptography.fields.encrypt(models.CharField(default='', help_text='API secret, client secret, or consumer secret', max_length=2000, verbose_name='secret key')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialtoken',
            name='token_encrypted',
            field=django_cryptography.fields.encrypt(models.TextField(default='', help_text='"oauth_token" (OAuth1) or access token (OAuth2)', verbose_name='token')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialtoken',
            name='token_secret_encrypted',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='"oauth_token_secret" (OAuth1) or refresh token (OAuth2)', verbose_name='token secret')),
        ),
    ]
