# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-09 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0006_migrate_encrypted_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='socialapp',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='socialapp',
            name='key',
        ),
        migrations.RemoveField(
            model_name='socialapp',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='socialtoken',
            name='token',
        ),
        migrations.RemoveField(
            model_name='socialtoken',
            name='token_secret',
        ),
    ]
