# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-09 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0007_auto_20200209_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='extra_data_encrypted',
            new_name='extra_data',
        ),
        migrations.RenameField(
            model_name='socialapp',
            old_name='client_id_encrypted',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='socialapp',
            old_name='key_encrypted',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='socialapp',
            old_name='secret_encrypted',
            new_name='secret',
        ),
        migrations.RenameField(
            model_name='socialtoken',
            old_name='token_encrypted',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='socialtoken',
            old_name='token_secret_encrypted',
            new_name='token_secret',
        ),
    ]
